name: Healthy Pull Request
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
env:
  NODE_VERSION: 18
jobs:
  test:
    if: github.event.pull_request.draft == false
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container: node:18-alpine
    name: Tests

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: kis_test
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Audit
        run: npm audit
      - name: Test
        run: npm run test
        env:
          DB_TEST: postgres://postgres:postgres@postgres:5432/kis_test
